// <auto-generated />
using System;
using KiemTraThichUng.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KiemTraThichUng.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225153021_init_identity_merge")]
    partial class init_identity_merge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.CauHinhDanhMuc.BoCauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdNguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int>("IdNguoiTao")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("MaBoCauHoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaiLieuThamKhao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenBoCauHoi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BoCauHoi");
                });

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.CauHinhDanhMuc.CauTruc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBoCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int>("IdNguoiTao")
                        .HasColumnType("int");

                    b.Property<int?>("IdParent")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("MaCauTruc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenCauTruc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CauTruc");
                });

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.CauHinhDeKiemTra.CauHinhDeKiemTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChuDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCauTruc")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<int>("IdNguoiTao")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("MaCauHinhDeKiemTra")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComputedColumnSql("RIGHT('0' + CAST(YEAR(NgayTao) % 100 AS VARCHAR(2)), 2) + RIGHT('0' + CAST(MONTH(NgayTao) AS VARCHAR(2)), 2) + RIGHT('0' + CAST(DAY(NgayTao) AS VARCHAR(2)), 2) + RIGHT(REPLICATE('0',9) + CAST(Id AS VARCHAR(9)),9)", true);

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<double>("PriorMean")
                        .HasColumnType("float");

                    b.Property<double>("PriorVariance")
                        .HasColumnType("float");

                    b.Property<double>("StandardErrorInitial")
                        .HasColumnType("float");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TenCauHinhDeKiemTra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ThetaKhoiTao")
                        .HasColumnType("float");

                    b.Property<double>("ThetaMax")
                        .HasColumnType("float");

                    b.Property<double>("ThetaMin")
                        .HasColumnType("float");

                    b.Property<int>("ThoiGianLamBaiGiay")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CauHinhDeKiemTra");
                });

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.CauHinhDeKiemTra.ChiTietCauHinhDeKiemTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCauHinhDeKiemTra")
                        .HasColumnType("int");

                    b.Property<int?>("IdLoaiCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("IdMucDoNhanThuc")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int>("IdNguoiTao")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChiTietCauHinhDeKiemTra");
                });

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.NganHangCauHoi.CauHoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CauHoiGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("DoKho")
                        .HasColumnType("float");

                    b.Property<double?>("DoKhoKhoiTao")
                        .HasColumnType("float");

                    b.Property<double?>("DoPhanLoai")
                        .HasColumnType("float");

                    b.Property<double?>("DoPhanLoaiKhoiTao")
                        .HasColumnType("float");

                    b.Property<string>("GhiChuDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiaiThich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCauHoiCha")
                        .HasColumnType("int");

                    b.Property<int>("IdCauTruc")
                        .HasColumnType("int");

                    b.Property<int>("IdLoaiCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("IdMucDoNhanThuc")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiDuyet")
                        .HasColumnType("int");

                    b.Property<int>("IdNguoiTao")
                        .HasColumnType("int");

                    b.Property<bool>("IsCauHoiCha")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKhongDao")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("MaCauHoi")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasComputedColumnSql("RIGHT('0' + CAST(YEAR(NgayTao) % 100 AS VARCHAR(2)), 2) + RIGHT('0' + CAST(MONTH(NgayTao) AS VARCHAR(2)), 2) + RIGHT('0' + CAST(DAY(NgayTao) AS VARCHAR(2)), 2) + RIGHT(REPLICATE('0',9) + CAST(Id AS VARCHAR(9)),9)", true);

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuotDung")
                        .HasColumnType("int");

                    b.Property<int>("SoLuotLam")
                        .HasColumnType("int");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.Property<string>("TieuDeVePhai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDeVeTrai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.NganHangCauHoi.CauTraLoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("IdNguoiCapNhat")
                        .HasColumnType("int");

                    b.Property<int>("IdNguoiTao")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDung")
                        .HasColumnType("bit");

                    b.Property<bool>("IsKhongDao")
                        .HasColumnType("bit");

                    b.Property<bool>("IsThietLapRieng")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVeTrai")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("MaCauTraLoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PhanTramDiem")
                        .HasColumnType("float");

                    b.Property<int?>("Stt")
                        .HasColumnType("int");

                    b.Property<int>("ViTriGachChan")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CauTraLoi");
                });

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.PhienKiemTra.ChiTietKetQuaKiemTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DoKhoLucThi")
                        .HasColumnType("float");

                    b.Property<double?>("DoPhanLoaiLucThi")
                        .HasColumnType("float");

                    b.Property<int>("IdCauHoi")
                        .HasColumnType("int");

                    b.Property<int?>("IdCauHoiCha")
                        .HasColumnType("int");

                    b.Property<int>("IdKetQuaKiemTra")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTraLoiDung")
                        .HasColumnType("bit");

                    b.Property<double>("PhanTramDiem")
                        .HasColumnType("float");

                    b.Property<double?>("StandardErrorAfter")
                        .HasColumnType("float");

                    b.Property<double?>("StandardErrorBefore")
                        .HasColumnType("float");

                    b.Property<double?>("ThetaAfter")
                        .HasColumnType("float");

                    b.Property<double?>("ThetaBefore")
                        .HasColumnType("float");

                    b.Property<double?>("ThetaTarget")
                        .HasColumnType("float");

                    b.Property<double?>("ThongTinCauHoi")
                        .HasColumnType("float");

                    b.Property<double?>("ThongTinTichLuyAfter")
                        .HasColumnType("float");

                    b.Property<double?>("ThongTinTichLuyBefore")
                        .HasColumnType("float");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ChiTietKetQuaKiemTra");
                });

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.PhienKiemTra.ChiTietLuaChon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCauTraLoi")
                        .HasColumnType("int");

                    b.Property<int>("IdChiTietKetQuaKiemTra")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTraLoiDung")
                        .HasColumnType("bit");

                    b.Property<string>("NoiDungCauTraLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PhanTramDiem")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ChiTietLuaChon");
                });

            modelBuilder.Entity("KiemTraThichUng.Domain.Entities.PhienKiemTra.KetQuaKiemTra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DiemSo")
                        .HasColumnType("float");

                    b.Property<int>("IdCauHinhDeKiemTra")
                        .HasColumnType("int");

                    b.Property<int?>("IdCauHoiHienTai")
                        .HasColumnType("int");

                    b.Property<int>("IdNguoiDung")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDat")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("StandardError")
                        .HasColumnType("float");

                    b.Property<double?>("Theta")
                        .HasColumnType("float");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("KetQuaKiemTra");
                });

            modelBuilder.Entity("KiemTraThichUng.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("VaiTroClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDungClaim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("NguoiDungLogin", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("NguoiDungVaiTro", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("NguoiDungToken", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("KiemTraThichUng.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("KiemTraThichUng.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KiemTraThichUng.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("KiemTraThichUng.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
